name: 'Docker Build'
description: 'Build Docker image'
inputs:
  path_dockerfile:
    description: "Path to the dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Image Name "
    required: false
  tag_name:
    description: "Tag Name"
    required: false

runs:
  using: 'composite'
  steps:
    - run: | 
        if [ -z "${{ inputs.tag_name }}" ]; then
          TAG=$(date +%s)
        else
          TAG="${{ inputs.tag_name }}"
        fi
        docker build . --file ${{ inputs.path_dockerfile }} --tag ${{ inputs.image_name }}:$TAG
      shell: bash