name: 'Maven Build'
description: 'Run mvn package with preset env vars'

runs:
  using: 'composite'
  steps:
    - name: Build with Maven
      env:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        JDBC_URL: jdbc:postgresql://localhost:5432/postgres
      run: mvn -B package --file pom.xml
      shell: bash